config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "home#index"

  resources :users, only: :show

  resources :artists do
    post :confirm, action: :confirm_new, on: :new
    member do
      get :gozyu_on
      post :confirm_edit
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # before_save :set_data
  mount_uploader :image, ImageUploader

  attr_accessor :image_cache

  validates :name, presence: true

  validates :furi_gana, presence: true
  validate :katanaka_valid

  validates :image, presence: true
  validates :place, presence: true
  validates :profile, presence: true
  validate :hp_valid
  validate :twitter_valid
  validate :youtube_valid

  belongs_to :user

  def self.gozyu_on(furi_gana)
    artists = Artist.order("furi_gana ASC")

    gozyu_on_artists = artists.select{|a| a.furi_gana =~ furi_gana}
  end

  private

  # def set_data
  #   self.hp= "未登録" if hp.blank?
  #   self.twitter = "未登録" if twitter.blank?
  #   self.youtube = "未登録" if youtube.blank?
  # end

  def katanaka_valid
    errors.add(:furi_gana, 'は全角カタカナで入力して下さい') unless furi_gana =~ /([ァ-ン]|ー)+/
  end

  def hp_valid
    return if hp.blank?
    errors.add(:hp, "のアドレスが無効な値です") unless hp =~ /\A#{URI::regexp(%w(http https))}\z/
  end

  def twitter_valid
    return if twitter.blank?

    if twitter !~ /^https:\/\/twitter.com\/\w+$/ || twitter.size > 35
      errors.add(:twitter, "が無効な値です")
    end
  end

  def youtube_valid
    return if youtube.blank?

    errors.add(:youtube, "以外のアドレスは登録できません") unless youtube.start_with?("https://www.youtube.com")
  end


end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def login_required
    redirect_to new_user_session_path, alert: "ログインして下さい" unless current_user
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :login_required, except: [:index, :show, :gozyu_on]
  before_action :set_current_user_artist, only: [:edit, :confirm_edit, :update, :destroy]

  FURI_GANA = [/^[ア-オ]+/,/^[カ-コ]+/,/^[サ-ソ]+/,/^[タ-ト]+/,/^[ナ-ノ]+/,/^[ハ-ホ]+/,
              /^[マ-モ]+/,/^[ヤ-ヨ]+/,/^[ラ-ロ]+/,/^[ワ-ン]+/]

  PER = 20

  def index
    @artists = Artist.all.order(created_at: :desc).page(params[:page]).per(PER)
  end

  def gozyu_on
    @name = params[:name]
    id = params[:id].to_i
    gozyu_on_artists = Artist.gozyu_on(FURI_GANA[id])

    @gozyu_on_artists = Kaminari.paginate_array(gozyu_on_artists).page(params[:page]).per(PER)
  end

  def new
    @artist = Artist.new
  end

  def confirm_new
    @artist = current_user.artists.new(artist_params)

    if !@artist.image.present?
      @artist.image.retrieve_from_cache! @artist.image_cache
    end

    @artist.image_cache = @artist.image.cache_name

    render :new unless @artist.valid?
  end

  def create
    @artist = current_user.artists.new(artist_params)
    @artist.image.retrieve_from_cache! @artist.image_cache

    if params[:back].present?
      render :new
      return
    end

    if @artist.save
      redirect_to user_path(current_user.id), notice: "登録完了"
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
  end

  def confirm_edit
    @artist.assign_attributes(artist_params)
    @artist.image.retrieve_from_cache! @artist.image_cache if @artist.image_cache.present?

    @artist.image_cache = @artist.image.cache_name

    render :edit unless @artist.valid?
  end

  def update
    @artist.assign_attributes(artist_params)
    @artist.image.retrieve_from_cache! @artist.image_cache if @artist.image_cache.present?

    if params[:back].present?
      render :edit
      return
    end

    if @artist.update(artist_params)
      redirect_to artist_path, notice: "更新完了"
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to user_path(current_user.id), notice: "削除しました"
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :furi_gana, :image, :image_cache, :place, :profile, :hp, :twitter, :youtube)
  end

  def set_current_user_artist
    @artist = current_user.artists.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @artists = current_user.artists
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/confirm_edit.html.slim
.container
  .main

    h1 更新内容の確認

    = form_with model: @artist, local: true, url: artist_path, method: :put do |f|
      table.table
        tbody
          tr
           th= Artist.human_attribute_name(:image)
           td= image_tag @artist.image_url
           = hidden_field_tag :"cache[image]", @artist.image.cache_name
          tr
           th= Artist.human_attribute_name(:name)
           td= @artist.name
           = f.hidden_field :name
          tr
           th= Artist.human_attribute_name(:furi_gana)
           td= @artist.furi_gana
           = f.hidden_field :furi_gana
          tr
           th= Artist.human_attribute_name(:place)
           td= @artist.place
           = f.hidden_field :place
          tr
          th= Artist.human_attribute_name(:profile)
          td= simple_format(@artist.profile)
          = f.hidden_field :profile
          tr
          th= Artist.human_attribute_name(:hp)
          td= @artist.hp
          = f.hidden_field :hp
          tr
          th= Artist.human_attribute_name(:twitter)
          td= @artist.twitter
          = f.hidden_field :twitter
          tr
          th= Artist.human_attribute_name(:youtube)
          td= @artist.youtube
          = f.hidden_field :youtube
      = f.hidden_field :image_cache
      = f.submit '戻る', name: 'back'
      = f.submit '更新'

app/views/artists/confirm_new.html.slim
.container
  .main

    h1 登録内容の確認

    = form_with model: @artist, local: true do |f|
      table.table
        tbody
          tr
           th= Artist.human_attribute_name(:image)
           td= image_tag @artist.image_url
           = hidden_field_tag :"cache[image]", @artist.image.cache_name
          tr
           th= Artist.human_attribute_name(:name)
           td= @artist.name
           = f.hidden_field :name
          tr
           th= Artist.human_attribute_name(:furi_gana)
           td= @artist.furi_gana
           = f.hidden_field :furi_gana
          tr
           th= Artist.human_attribute_name(:place)
           td= @artist.place
           = f.hidden_field :place
          tr
          th= Artist.human_attribute_name(:profile)
          td= simple_format(@artist.profile)
          = f.hidden_field :profile
          tr
          th= Artist.human_attribute_name(:hp)
          td= @artist.hp
          = f.hidden_field :hp
          tr
          th= Artist.human_attribute_name(:twitter)
          td= @artist.twitter
          = f.hidden_field :twitter
          tr
          th= Artist.human_attribute_name(:youtube)
          td= @artist.youtube
          = f.hidden_field :youtube
      = f.hidden_field :image_cache
      = f.submit '戻る', name: 'back'
      = f.submit '登録'

app/views/artists/edit.html.slim
.container
  .main

    h1 アーティスト編集

    .nav.justify-content-end
      = link_to 'マイページへ', user_path(current_user.id), class: 'nav-link'

    - @artist.errors.full_messages.each do |er|
      p style="color :red;"
        |*
        = er

    = form_with model: @artist,local: true, url: confirm_edit_artist_path, method: :post do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', id: 'artist_name'

      .form-group
        = f.label :furi_gana
        = f.text_field :furi_gana, class: 'form-control', id: 'artist_furi_gana'

      .form-group
        p = image_tag @artist.image_url if @artist.image
        = f.label :image
        = f.file_field :image, class: 'form-control', id: 'artist_image'
        = f.hidden_field :image_cache

      .form-group
        = f.label :place
        = f.text_field :place, class: 'form-control', id: 'artist_place'

      .form-group
        = f.label :profile
        = f.text_area :profile, class: 'form-control', id: 'artist_profile'

      .form-group
        = f.label :hp
        = f.text_field :hp, class: 'form-control', id: 'artist_hp'

      .form-group
        = f.label :twitter
        p
          |(https://twitter.com/ユーザー名)
        = f.text_field :twitter, class: 'form-control', id: 'artist_twitter'

      .form-group
        = f.label :youtube
        = f.text_field :youtube, class: 'form-control', id: 'artist_youtube'

      = f.submit '確認', class: 'btn btn-primary'

app/views/artists/gozyu_on.html.slim
.container
  .main
    h2 = @name
    p
      = link_to "アーティスト一覧へ", artists_path

    .row
      - if @gozyu_on_artists.present?
        - @gozyu_on_artists.each do |artist|
          .col-lg-4.text-center
            = link_to artist do
              = image_tag artist.image_url
              p = artist.name
      - else
        p 登録アーティストはありません
    = paginate @gozyu_on_artists

app/views/artists/index.html.slim
.container
  .main
    h1 アーティスト一覧


    .nav-item.dropdown style="padding:50px;"
      a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
        |  五十音検索
      .dropdown-menu[aria-labelledby="navbarDropdown"]
        .dropdown-item
          = link_to 'ア行', controller: 'artists', action: 'gozyu_on', id: 0, name: "ア行"
        .dropdown-item
          = link_to 'カ行', controller: 'artists', action: 'gozyu_on', id: 1, name: "カ行"
        .dropdown-item
          = link_to 'サ行', controller: 'artists', action: 'gozyu_on', id: 2, name: "サ行"
        .dropdown-item
          = link_to 'タ行', controller: 'artists', action: 'gozyu_on', id: 3, name: "タ行"
        .dropdown-item
          = link_to 'ナ行', controller: 'artists', action: 'gozyu_on', id: 4, name: "ナ行"
        .dropdown-item
          = link_to 'ハ行', controller: 'artists', action: 'gozyu_on', id: 5, name: "ハ行"
        .dropdown-item
          = link_to 'マ行', controller: 'artists', action: 'gozyu_on', id: 6, name: "マ行"
        .dropdown-item
          = link_to 'ヤ行', controller: 'artists', action: 'gozyu_on', id: 7, name: "ヤ行"
        .dropdown-item
          = link_to 'ラ行', controller: 'artists', action: 'gozyu_on', id: 8, name: "ラ行"
        .dropdown-item
          = link_to 'ワ行', controller: 'artists', action: 'gozyu_on', id: 9, name: "ワ行"

    .row
      - @artists.each do |artist|
        .col-lg-4.text-center
          = link_to artist do
            = image_tag artist.image_url
            p = artist.name
    p = paginate @artists

app/views/artists/new.html.slim
.container
  .main
    h1 アーティスト登録
    p ＊は必須項目です

    .nav.justify-content-end
      = link_to 'マイページへ', user_path(current_user.id), class: 'nav-link'

    - @artist.errors.full_messages.each do |er|
      p style="color :red;"
        |*
        = er

    = form_with model: @artist,local: true, url: confirm_new_artist_path do |f|
      .form-group
        | ＊
        = f.label :name
        = f.text_field :name, class: 'form-control', id: 'artist_name'

      .form-group
        | ＊
        = f.label :furi_gana
        = f.text_field :furi_gana, class: 'form-control', id: 'artist_furi_gana'

      .form-group
        | ＊
        = f.label :image
        = f.file_field :image, class: 'form-control', id: 'artist_image'
        = f.hidden_field :image_cache

      .form-group
        | ＊
        = f.label :place
        = f.text_field :place, class: 'form-control', id: 'artist_place'

      .form-group
        | ＊
        = f.label :profile
        = f.text_area :profile, class: 'form-control', id: 'artist_profile'

      .form-group
        = f.label :hp
        = f.text_field :hp, class: 'form-control', id: 'artist_hp'

      .form-group
        = f.label :twitter
        p
          |(https://twitter.com/ユーザー名)
        = f.text_field :twitter, class: 'form-control', id: 'artist_twitter'

      .form-group
        = f.label :youtube
        = f.text_field :youtube, class: 'form-control', id: 'artist_youtube'

      = f.submit '確認', class: 'btn btn-primary'

app/views/artists/show.html.slim
.container
  .main
    nav.nav
      .nav-link.active

      - if user_signed_in? && current_user.id == @artist.user.id
        .nav-link
          p = link_to "アーティスト一覧へ", artists_path
        .nav-link
          p = link_to "マイページへ", user_path(current_user.id)
        .nav-link
          p = link_to "編集する", edit_artist_path(@artist.id)
        .nav-link
          p = link_to "削除する", @artist, method: :delete, data:{confirm: "#{@artist.name}を削除してよろしですか？"}
      - else
        .nav-link
          p = link_to "戻る", :back


    .card.text-center
      .card-header
        h1 = @artist.name
        p = @artist.furi_gana
      .card-body
        .card-text
        = image_tag @artist.image_url
      .card-header
        | 活動地域
      .card-body
        h4.card-text
          = @artist.place
      .card-header
        | プロフィール
      .card-body
        p.card-text
          = @artist.profile
      .card-header
        | HP
      .card-body
        p.card-text
          - unless @artist.hp == "未登録"
            = (link_to "#{@artist.hp}", "#{@artist.hp}")
          - else
            = @artist.hp
      .card-header
        | Twitter
      .card-body
        p.card-text
          - unless @artist.twitter == "未登録"
            = (link_to "#{@artist.twitter}", "#{@artist.twitter}")
          - else
            = @artist.twitter
      .card-header
        | Youtube
      .card-body
        p.card-text
          - unless @artist.youtube == "未登録"
            = (link_to "#{@artist.youtube}", "#{@artist.youtube}")
          - else
            = @artist.youtube

app/views/home/index.html.slim
.jumbotron.jumbotron-extend
  .container-fluid.jumbotron-container.text-center
    h1 style="color :white;"
      | Artist's Moment
    = link_to 'アーティスト一覧', artists_path, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Artist's Moment
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
  body

    nav.navbar.navbar-expand-lg.navbar-light.bg-light
      a.navbar-brand href="/"  TOP
      button.navbar-toggler aria-controls="navbarNav" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNav" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      #navbarNav.collapse.navbar-collapse
        ul.navbar-nav
          - if user_signed_in?
            li.nav-link
              = link_to "マイページ", user_path(current_user.id)
            li.nav-link
              = link_to "ログアウト", destroy_user_session_path, method: :delete
          - else
            li.nav-link
              = link_to "ユーザー登録", new_user_registration_path, class: "post"
            li.nav-link
              = link_to "ログイン", new_user_session_path, class: "post"




    .container
      - flash.each do |key,value|
        - key = "info" if key == "notice"
        - key = "danger" if key == "alert"
        = content_tag :div, value, class: "alert alert-#{key}"
    = yield

app/views/users/show.html.slim
.container
  .main
    h2
      - if current_user.name
        = current_user.name
        | さんのページ
      -else
        | ユーザー : (No.
        = current_user.id
        | )さんのページ

    h3.text-center style="padding:50px 0px;"
      = link_to '新規アーティスト登録', new_artist_path

    p = link_to "アーティスト一覧へ", artists_path



    .list-group
      h2.list-group-item
        | 登録済みアーティスト
      - @artists.each do |artist|
        li.list-group-item
          = link_to artist.name, artist_path(artist.id)